WINLOGBEAT_INDEX = "winlogbeat-*"
SYSMON_PROVIDER_NAME = "Microsoft-Windows-Sysmon"
MICROSOFT_WINDOWS_DNSCLIENT_PROVIDER_NAME="Microsoft-Windows-DNS-Client"
MICROSOFT_WINDOWS_POWERSHELL_PROVIDER_NAME="Microsoft-Windows-PowerShell"